config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  devise_for :users
  resources :tags
  resources :topics do
    resources :posts do
      get :post_user_status, on: :member
      resources :comments do
        member do
          get :comment_rate_show
          post :user_comment_rate
        end
      end
      resources :ratings
    end
  end
  get :devise, to: 'topics#devise'
  get '/users', to: 'users#index', :defaults => {:format => 'json'}
  resources :posts, :only => :index
  root "topics#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: true
  belongs_to :user
  has_many :user_comment_ratings #the associated model with user and comment
  has_many :users, through: :user_comment_ratings, dependent: :destroy
#===============================validATION==============================================================================
  validates_presence_of :name, :body
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_topic
  before_action :set_post
  before_action :set_comment, except: [:index, :create, :new]
  load_and_authorize_resource :topic
  load_and_authorize_resource :post
  load_and_authorize_resource :comment, through: [:topic, :post], only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = @post.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html {redirect_to topic_post_path(@topic, @post), notice: 'Comment was successfully created.'}

      else
        format.html {render :new, alert: "Comment has not been created"}
        format.js {render :create}
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html {redirect_to topic_post_comments_path(@topic, @post, @comment), notice: 'Comment was successfully updated.'}
        format.json {render :show, status: :ok, location: @comment}
      else
        format.html {render :edit}
        format.json {render json: @comment.errors, status: :unprocessable_entity}
      end
    end
  end

  def comment_rate_show
    @rate_comment = @comment.user_comment_ratings.includes(:user)
  end

  def user_comment_rate
     @comment_ratings = @comment.user_comment_ratings.create(comment_rate_params)
    # p @comment_ratings.errors.details
    if @comment_ratings.save
      flash[:notice] = "successfully updated comment's rating by user"
    else
      flash[:alert] = "You have already rated the comment"
    end
    redirect_to topic_post_path(@topic, @post)
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html {redirect_to topic_post_path(@topic, @post), alert: 'Comment was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def set_post
    @post = @topic.posts.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The Record you were looking for could not be found."
    redirect_to topic_post_path(@topic,@post)
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:name, :body).merge(user_id: current_user.id)
  end

  def comment_rate_params
    params.fetch(:user_comment_rating,{}).permit(:rate).merge(user_id: current_user.id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for  [@topic,@post,comment], remote: true   do |form| %>
      <div class="form-group">
        <div class="control-label col-md-1 ">
          <%= form.label :name %>
        </div>
        <div class="col-md-11 ">
          <%= form.text_field :name, :value=>current_user.email ,class:'form-control error-name-field', placeholder: "Name" %>
        </div>
        <span id="commentNameBlock" class="text-danger"></span>
      </div>
      <div class="form-group">
        <div class="control-label col-md-1 ">
          <%= form.label :body %>
        </div>
        <div class="col-md-11 ">
          <%= form.text_area :body, rows:5,class:'form-control error-desc-field', placeholder: "Write your comment" %>
        </div>
        <span id="commentBodyBlock" class="text-danger"></span>
      </div>

      <div class="form-group">
        <div class="col-md-offset-1 col-md-6">
          <%= form.button "Comment", class: 'btn btn-success btn-lg',data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>Adding comments... "}  %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/comment_rate_show.html.erb
<div class="row">
  <div class="col-4">
    <table class="table table-striped table-dark">
      <thead >
      <tr>
        <th scope="col">User</th>
        <th scope="col">Rate</th>
      </tr>
      </thead>
      <tbody>
      <% if @rate_comment.empty? %>
        <td><strong>please rate the comment</strong></td>
      <% else %>
        <% @rate_comment.each do |l| %>
          <tr>
            <td><%= l.user.email %></td>
            <td><%= l.rate %></td>
          </tr>

        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
 <div class="offset-7 col-1">
   <%=link_to "Back", topic_post_path(@topic,@post), class: "btn-sm btn-dark"%>
 </div>
</div>



app/views/comments/create.js.erb
<%if @comment.errors.any? %>
$(".error").remove();
$("#commentNameBlock").append('<div class="error"><%= escape_javascript(@comment.errors["name"][0])%></div>');
$("#commentBodyBlock").append('<div class="error"><%= escape_javascript(@comment.errors["body"][0])%></div>');
<%if @comment.errors["name"][0].nil? %>
$(".error-name-field").removeClass("is-invalid");
//$(".error-name-field").addClass("is-valid")
<%else %>
//$(".error-name-field").removeClass("is-valid");
$(".error-name-field").addClass("is-invalid")
<%end %>
<% if @comment.errors["body"][0].nil? %>
$(".error-desc-field").removeClass("is-invalid");
//$(".error-desc-field").addClass("is-valid")
<% else %>
//$(".error-desc-field").removeClass("is-valid");
$(".error-desc-field").addClass("is-invalid")
<%end %>
<%end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>


<%= link_to 'Back', topic_post_comments_path,class: "btn btn-primary btn-sm btn-space" %>

app/views/comments/index.html.erb
<h1>All Comments</h1>
<%= link_to 'New Comment', new_topic_post_comment_path(@topic,@post), class: "btn btn-success btn-sm new-post-btn" %>

    <% @comments.each do |comment| %>
  <div class="wel wel-lg edit-delete-btb">
    <div class="post-name">
        <%= comment.name %>
    </div>
    <%= link_to 'Show',  topic_post_comment_path(@topic,@post,comment), method: :get, class: "btn btn-primary btn-sm btn-space" %>
    <%= link_to 'Edit', edit_topic_post_comment_path(@topic,@post,comment), method: :get, class: "btn btn-secondary  btn-sm btn-space" %>
    <%= link_to 'Destroy', topic_post_comment_path(@topic,@post,comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm btn-space" %>
      </div>
    <% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%#= link_to 'Back', topic_post_comment_path %>

app/views/comments/show.html.erb
  <h1 class="post-detail-name"><%=@comment.name %></h1>
  <div class="post-body">
    <%=@comment.body %>
  </div>


  <%= link_to 'Edit', edit_topic_post_comment_path(@topic,@post,@comment),class: "btn btn-primary btn-sm btn-space" %>

  <%= link_to 'Delete', topic_post_comment_path(@topic,@post,@comment), method: :delete, data: {confirm: "Are you sure"},class: "btn btn-danger btn-sm btn-space"%>