config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  devise_for :users
  resources :tags
  resources :topics do
    resources :posts do
      get :post_user_status, on: :member
      resources :comments do
        member do
          get :comment_rate_show
          post :user_comment_rate
        end
      end
      resources :ratings
    end
  end
  get :devise, to: 'topics#devise'
  get '/users', to: 'users#index', :defaults => {:format => 'json'}
  resources :posts, :only => :index
  root "topics#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord

  #======================================Associations===================================================================
  belongs_to :user
  has_many :posts , dependent: :destroy
 #========================================Validations===================================================================
  validates_presence_of :name
  validates :name, :uniqueness => {:case_sensitive => false}
  validates :name, length: {maximum: 20}

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, except: [:index, :new, :create,:devise]
  before_action :topics_all, only: [:index, :create, :update]
  load_and_authorize_resource :only => [:edit, :update, :destroy]
  # GET /topics
  # GET /topics.json
  # sidekiq bundle exec sidekiq -q default -q mailers
  def index
  end

  def show

  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    respond_to do |format|
      if @topic.save
        # TopicMailer.delay.welcome_topic(current_user,@topic)
        EmailSenderWorker.perform_async(current_user.id, @topic.id)
        # TopicMailer.with(user: current_user,topic: @topic).welcome_topic.deliver_later
        format.html{redirect_to topics_path, notice: "Topic has been created"}
        format.js {render :create}
        format.json {render :show, status: :created, location: @topic}

      else
        format.html{render :new, notice: "Topic not been created"}
        format.js {render :create}
        format.json {render json: @topic.errors, status: :unprocessable_entity}

      end
    end
  end
  def devise
    # if request.env['HTTP_USER_AGENT'].downcase.match(/mac/i)
    #   redirect_to 'https://itunes.apple.com/us/app/apple-store/id375380948?mt=8'
    # elsif request.env['HTTP_USER_AGENT'].downcase.match(/windows/i)
    #   redirect_to 'https://www.microsoft.com/en-in/store/apps/windows'
    # elsif request.env['HTTP_USER_AGENT'].downcase.match(/android/i)
    #   redirect_to 'https://play.google.com/store?hl=en'
    # else
    #   redirect_to root_path
    # end
# p request.env['HTTP_USER_AGENT']
p  request.user_agent.downcase
     redirect_to case request.user_agent.downcase
                when /mac/i     then 'https://itunes.apple.com/us/app/apple-store/id375380948?mt=8'
                when /windows/i then 'https://www.microsoft.com/en-in/store/apps/windows'
                when /android/i then 'https://play.google.com/store?hl=en'
                else
                  root_path
                end
  end
  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html {redirect_to topics_path, notice: "Topic was successfully updated"}
        format.js {render :create}
        format.json {render :show, status: :ok, location: @topic}
      else
        format.html {redirect_to topics_path, notice: "Topic not been updated"}
        format.js {render :create}
        format.json {render json: @topic.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html {redirect_to topics_url, alert: 'Topic was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The Topic you were looking for could not be found."
    redirect_to topics_path

  end

  def topics_all
    @topics = Topic.order(created_at: :desc).includes(:user).paginate(page: params[:page], per_page: 8)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:name).merge(user_id: current_user.id)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
 <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Topic</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
 <%= bootstrap_form_for  @topic, remote: true do |form| %>
      <div class="modal-body">
          <!--  ======================================Form for topic=============================================================-->
          <div class="form-group ">
<!--            <div class="control-label col-md-1">-->
              <%#= form.label :name %>
<!--            </div>-->
            <div class="col-md-11 ">
              <%= form.text_field :name, class: 'form-control error-field ', placeholder: "Name" %>
              <span id="topicNameBlock" class="text-danger"></span>
            </div>

          </div>
      </div>
      <!-- Modal footer -->
      <div class="modal-footer">
            <%= form.submit class: 'btn btn-success '%>
            <button type="button" class="btn btn-danger " data-dismiss="modal">Close</button>
        <% end %>
      </div>

app/views/topics/_topic.html.erb
<% @topics.each do |topic| %>
  <%= link_to topic_posts_path(topic), class:"show-topic" do %>
  <div class="card-deck mb-3 ">
    <div class="card  topic_card">
      <div class="card-body">
        <h3 class="card-title font-weight-bold"><%= topic.name %></h3>
        <% if topic.user.present? %>
          <p class="card-text">
            <small class="text-muted">Created By:<%= topic.user.email %></small>
          </p>
        <% end %>

      <%if can? :update, topic %>
<!--      <div class="card-footer" id="edit-topic-block">-->
        <% if can? :update, topic %><%= link_to 'Edit', edit_topic_path(topic), method: 'get', remote: true,'data-toggle' => "modal", 'data-target' => '#myModal', data: {disable_with: "<i class='fa fa-spinner fa-pulse'></i>Edit Topic... "}, class: "btn btn-secondary btn-sm btn-space" %>
        <% end %>
        <% if can? :destroy, topic %><%= link_to 'Delete', topic, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm btn-space" %>
        <% end %>
<!--      </div>-->
        <%end %>
      </div>
    </div>
  </div>
      <%end %>
<% end %>

app/views/topics/create.js.erb
<% if @topic.errors.any? %>
$(".error").remove();
$("#topicNameBlock").append('<div class="error"><%= escape_javascript(@topic.errors['name'][0])%></div>');
<% unless @topic.errors['name'][0].nil?%>
$(".error-field").addClass("is-invalid")
<% end %>
<% else %>
$("#myModal").modal('hide');
$('#index-topic').html("<%=j render @topic %>");
alert("Topic is created successfully");
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'topics/form' %>

<%= link_to 'Back', topics_path, class: "btn-dark btn-sm" %>

app/views/topics/edit.js.erb
$("#myModal").find(".modal-content").html("<%= j (render 'topics/form') %>");
$("#myModal").modal('show');

app/views/topics/index.html.erb
<div class="row">
  <div class="col-9">
    <h1 class="font-weight-bold">Listing All Topics <span class="badge badge-secondary"><%= "#{@topics.length}" %></span></h1>
  </div>
  <div class="col-3">
    <%= link_to 'New Topic', new_topic_path, class: "btn btn-success btn-sm float-right",id:"topic-new", remote: true,'data-toggle' => "modal", 'data-target' => '#myModal', data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>New Topic... "} %>
  </div>
</div>
<!--===================model to render form==========================================================================-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" >
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>
<!--=================================================================================================================-->
<div id="index-topic">
  <%= render 'topics/topic' %>
</div>
<%= will_paginate @topics, list_classes: %w(pagination justify-content-center), previous_label: "Previous", next_label: "Next", inner_window: 1, outer_window: 0 %>

app/views/topics/new.html.erb
<h1>New Topic</h1>
<%= render 'topics/form'%>

<%= link_to 'Back', topics_path,class: "btn btn-secondary btn-sm" %>

app/views/topics/new.js.erb
//$('#edit-topic-block a').hide().parent();
//$('#topic-new a').hide().parent().append("<#%= j render 'form' %>");
//$('#myModal').modal('show');
$("#myModal").find(".modal-content").html("<%= j (render 'topics/form') %>");
$("#myModal").modal('show');





app/views/topics/show.html.erb
<topic class="detail-post">

  <h1 class="post-detail-name"><%=@topic.name %></h1>

  <%if can? :update, @topic%><%= link_to 'Edit', edit_topic_path(@topic),class: "btn btn-primary btn-sm btn-space" %><%end %>

  <%if can? :destroy, @topic %><%= link_to 'Delete', topic_path(@topic), method: :delete, data: {confirm: "Are you sure"},class: "btn btn-danger btn-sm btn-space"%><% end %>

  <%= link_to 'Back', topics_path,class: "btn btn-secondary btn-sm btn-space" %>





</topic>