config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  devise_for :users
  resources :tags
  resources :topics do
    resources :posts do
      get :post_user_status, on: :member
      resources :comments do
        member do
          get :comment_rate_show
          post :user_comment_rate
        end
      end
      resources :ratings
    end
  end
  get :devise, to: 'topics#devise'
  get '/users', to: 'users#index', :defaults => {:format => 'json'}
  resources :posts, :only => :index
  root "topics#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings, dependent: :destroy
    validates :tagname, :uniqueness => {:case_sensitive => false},if: :tag_required

  def tag_required
    tagname.present?
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.order(created_at: :desc)
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag_post = @tag.posts.includes(:user,:topic)
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html {redirect_to @tag, notice: 'Tag was successfully created.'}
        format.json {render :show, status: :created, location: @tag}
      else
        format.html {render :new}
        format.json {render json: @tag.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html {redirect_to @tag, notice: 'Tag was successfully updated.'}
        format.json {render :show, status: :ok, location: @tag}
      else
        format.html {render :edit}
        format.json {render json: @tag.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html {redirect_to tags_url, alert: 'Tag was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The Tag you were looking for could not be found."
    redirect_to root_path
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require(:tag).permit(:tagname)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <%# if tag.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>-->

<!--      <ul>-->
        <%# tag.errors.full_messages.each do |message| %>
<!--          <li><%#= message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

  <div class="field">
    <%= form.label :tagname %>
    <%= form.text_field :tagname %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<div class="row">
<table class="table table-bordered table-dark col-4">
  <thead>
    <tr>
      <th>List of Tags</th>
      <th colspan="2">Edit/Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%=link_to tag.tagname, tag, class: "btn btn-primary" %></td>
        <td colspan="2"><%= link_to 'Edit', edit_tag_path(tag), class: "btn btn-secondary" %>
        <%= link_to 'Destroy', tag, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="col-8 float-right">
  <%= link_to 'Back', :back, class: "btn float-right btn-dark btn-sm btn-space" %>
</div>
</div>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<div class="row">
  <div class="col-11">
    <h1>Listing the posts related to<span class="text-info text-uppercase badge">#<%=@tag.tagname %></span> </h1>
  </div>
<div class="col-1">
  <%=link_to "Back", :back ,class:"btn btn-dark btn-sm" %>
</div>
</div>

<div class="index-tag">
  <%@tag_post.each do |tag_posts| %>
    <%= link_to topic_post_path(tag_posts.topic_id, tag_posts), class:"show-topic" do %>
      <div class="card-deck mb-3">
        <div class="card topic_card">
          <div class="card-body">
            <% if current_user.post_reads.include?(tag_posts) %>
              <p class="font-weight-bold text-danger text-right">Read </p>
            <% else %>
              <p class="font-weight-bold text-success text-right">UnRead</p>
            <% end %>
            <h3  class="card-title font-weight-bold "><%= tag_posts.name %></h3>
              <% if  tag_posts.topic.present? %><h4><%= "(#{tag_posts.topic.name})" %></h4><% end %>
            <%if tag_posts.user.present? %>
              <p class="card-text"><small class="text-muted">Created By:<%= tag_posts.user.email %></small></p>
            <%end%>
            <%if  can? :manage, tag_posts %>
              <% if can? :update, tag_posts %>  <%= link_to 'Edit', edit_topic_post_path(tag_posts.topic_id, tag_posts), method: :get, class: "btn btn-secondary  btn-sm btn-space" %><% end %>
              <% if can? :destroy, tag_posts %><%=link_to 'Delete', topic_post_path(tag_posts.topic_id, tag_posts), method: :delete, data: {confrim: 'Are you Sure?'}, class: "btn btn-danger btn-sm btn-space" %><%end %>
            <%end%>
          </div>
        </div>
      </div>
    <%end %>
  <% end %>
</div>