config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'
  devise_for :users
  resources :tags
  resources :topics do
    resources :posts do
      get :post_user_status, on: :member
      resources :comments do
        member do
          get :comment_rate_show
          post :user_comment_rate
        end
      end
      resources :ratings
    end
  end
  get :devise, to: 'topics#devise'
  get '/users', to: 'users#index', :defaults => {:format => 'json'}
  resources :posts, :only => :index
  root "topics#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  #====================== Relations ====================================================================================

  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :taggings  #the associated model with tag and post
  has_many :tags, through: :taggings, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_and_belongs_to_many :users
  has_attached_file :image,default_url: ':style/missing_img.png', styles: {small: "64*64#", med: "100*100>", large: "200*200>"}
  #====================== Validations ==================================================================================
  validates_presence_of :name, :description
  validates :name, length: {maximum: 20}
  validates :name, :uniqueness => {:case_sensitive => false}
  validates :description, length: {minimum: 25}
  validates_attachment_content_type :image, content_type:/\Aimage\/.*\z/, message: "Please Upload valid images"
  #===============================Tagging===============================================================================

  accepts_nested_attributes_for :tags, allow_destroy: true, reject_if: proc { |attributes| attributes['tagname'].blank? }
#=====================================Scope for date====================================================================
  scope :search_date,->(start_date, end_date) {where(created_at: start_date..end_date)}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_topic, except: [:index]
  before_action :set_post, only: [:edit, :update, :destroy, :post_user_status, :show]
  load_and_authorize_resource :topic
  load_and_authorize_resource :post, through: :topic, only: [:show, :edit, :update, :destroy]

  def index
    params[:start_date] = ((params[:start_date].present?) ? params[:start_date] : Date.today - 7)
    params[:end_date] = ((params[:end_date].present?) ? params[:end_date] : Date.today)
    if params[:start_date] >= params[:end_date]
      redirect_back(fallback_location: root_path)
      flash[:alert] = "date is out of range"
    end
    @posts = ((params[:topic_id].present?) ? @topic.posts : Post.all)
    @posts = @posts.search_date(params[:start_date], params[:end_date])

    if @posts.present?
      @posts = @posts.includes(:user).paginate(page: params[:page], per_page: 6).order(created_at: :desc)
    end
  end

  def show

    @ratecounts = Hash.new
    @ratecounts = {1 => 0, 2 => 0, 3 => 0, 4 => 0, 5 => 0}
    #raings by group_by
    @rating_count_groupby = @post.ratings.group_by(&:rate)
    @result1 = @ratecounts.merge(@rating_count_groupby) {|key, val1, val2| val1 + val2.count}
    #rating by group
    # @rating_count_group = @post.ratings.group(:rate).count
    # @result = @ratecounts.merge(@rating_count_group) {|key, val1, val2| val1 + val2}
    @rate_avg = @post.ratings.average(:rate)
    @comments = @post.comments.includes(:user)
  end

  def new
    @post = @topic.posts.new
  end

  def edit
  end

  def create
    @post = @topic.posts.new(post_params)
    respond_to do |format|
      if @post.save
        @posts = @topic.posts.paginate(page: params[:page], per_page: 6).order(created_at: :desc)
        format.html {redirect_to topic_posts_path, notice: "Post has been created"}
        format.js {render :create}
        format.json {render :show, status: :created, location: @post}
      else
        format.html {render :new, notice: "Post not been created"}
        format.js {render :create}
        format.json {render json: @post.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        @posts = @topic.posts.order(updated_at: :desc).paginate(page: params[:page], per_page: 6)
        format.html {redirect_to topic_posts_path, notice: "Post has been updated"}
        format.js {render :create}
        format.json {render :show, status: :created, location: @post}
      else
        format.html {render :edit, notice: "Post not been created"}
        format.js {render :create}
        format.json {render json: @post.errors, status: :unprocessable_entity}
      end
    end
  end

  def post_user_status
    unless @post.users.include?(current_user)
      @post.users << current_user
      head :no_content
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html {redirect_to topic_posts_path, alert: 'Post was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def set_post
    @post = @topic.posts.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The Post you were looking for could not be found."
    redirect_to topic_posts_path(@topic)
  end

  def post_params
    params.require(:post).permit(:name, :description, :image, :tag_ids => [], tags_attributes: [:tagname]).merge(user_id: current_user.id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_date.html.erb
<!--<h3 class="text-center font-weight-bold">Filter Post</h3>-->
  <div class="col-md-12">
  <%= form_with url: posts_path(),method: :get,local: :true do |form|%>
      <div class="form-inline align-items-center">
        <div class="form-group">
          <%= form.label :from %>
          <div class="col-3">
            <%= form.date_field :start_date,:value=>params[:start_date],class: "form-control"%>
          </div>
        </div>
        <div class="form-group">
          <%= form.label :to %>
          <div class="col-3  ">
            <%= form.date_field :end_date,:value=>params[:end_date],class: "form-control"%>
          </div>
        </div>
        <div class="form-group">
          <div class="align-content-center">
        <%= hidden_field_tag "topic_id",params[:topic_id] if params[:topic_id].present?  %>
        <%= form.submit "search", class: "btn btn-sm btn-primary" %>
          </div>
        </div>
      </div>

    <% end %>
  </div>

<!--</div>-->

app/views/posts/_form.html.erb
<div class="modal-header">
  <h4 class="modal-title">Post</h4>
  <button type="button" class="close" data-dismiss="modal">&times;</button>
</div>
<%= bootstrap_form_for [@topic, @post], remote: true, html: {multipart: true} do |form| %>
  <div class="modal-body">
    <!--===========================================form for post=======================================================-->
    <div id="new-post">
      <div class="form-group">
        <div class="col-md-11 ">
          <%= form.text_field :name, class: 'form-control error-name-field', placeholder: "Name" %>
          <span id="postNameBlock" class="text-danger"></span>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-11  error-desc-field">
          <%= form.text_area :description, rows: 3, class: 'form-control error-desc-field', placeholder: "Write your post" %>
          <span id="postDescBlock" class="text-danger"></span>
        </div>

      </div>
      <div class="form-group">
        <div class="col-md-11">
          <%= form.file_field :image %>
          <span id="postImgBlock" class="text-danger"></span>
        </div>

      </div>
      <%= form.fields_for :tags, @post.tags.build do |tagg| %>
        <div class="form-group">
          <div class="col-md-11">
            <%= tagg.text_field :tagname, class: 'form-control errorTagfield', placeholder: "Tag Name" %>
            <span id="postTagBlock" class="text-danger"></span>
          </div>
        </div>
      <% end %>
      <div class="col-md-11">
        <%= form.collection_select :tag_ids, Tag.all.order('tagname'), :id, :tagname, {}, {multiple: true} %>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <%= form.submit class: 'btn btn-success' %>
    <button type="button" class="btn btn-danger " data-dismiss="modal">Close</button>

  </div>
<% end %>

app/views/posts/_post.html.erb
<% @posts.each do |post| %>
  <%= link_to topic_post_path(post.topic_id, post), class:"show-topic" do %>
  <div class="card-deck mb-3 ">
    <div class="card topic_card">
      <div class="card-body">
        <% if current_user.post_reads.include?(post) %>
          <p class="font-weight-bold text-danger text-right">Read </p>
        <% else %>
          <p class="font-weight-bold text-success text-right">UnRead</p>
        <% end %>
        <h3 class="card-title font-weight-bold text-uppercase"><%= post.name %></h3>
          <% if @topic.present? %>
          <h4><%= "(#{@topic.name})" %></h4>
          <% end %>
        <%if post.user.present? %>
          <p class="card-text"><small class="text-muted">Created By:<%= post.user.email %></small></p>
        <%end%>
      <%if  can? :manage, post %>
<!--      <div class="card-footer" id="edit-post-block">-->
          <% if can? :update, post %><%= link_to 'Edit', edit_topic_post_path(post.topic_id, post), method: :get, remote: true, data: {disable_with: "<i class='fa fa-spinner fa-pulse'></i>Edit Post... "}, class: "btn btn-secondary  btn-sm btn-space" %>
          <% end %>
          <% if can? :destroy, post %><%= link_to 'Delete', topic_post_path(post.topic_id, post), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm btn-space", id: "delete_button" %>
          <% end %>
<!--      </div>-->
        <%end %>
      </div>
    </div>
  </div>
<% end %>
<%end %>

app/views/posts/create.js.erb
<%if @post.errors.any? %>
$(".error").remove();
$("#postNameBlock").append('<div class="error"><%= escape_javascript(@post.errors['name'][0])%></div>');
$("#postDescBlock").append('<div class="error"><%= escape_javascript(@post.errors['description'][0])%></div>');
$("#postImgBlock").append('<div class="error"><%= escape_javascript(@post.errors['image'][1])%></div>');
$("#postTagBlock").append ('<div class="error"><%= escape_javascript(@post.errors.messages[:'tags.tagname'][0])%></div>');
<%if @post.errors['name'][0].nil?%>
$(".error-name-field").removeClass("is-invalid");
<%else %>
$(".error-name-field").addClass("is-invalid");
<%end %>
<% if @post.errors['description'][0].nil?%>
$(".error-desc-field").removeClass("is-invalid");
<% else %>
$(".error-desc-field").addClass("is-invalid");
<%end %>
<% if @post.errors.messages[:'tags.tagname'][0].nil?%>
$(".errorTagfield").removeClass("is-invalid");
<% else %>
$(".errorTagfield").addClass("is-invalid");
<%end %>
<%else %>
$("#post-modal").modal('hide');
$('#index-post').html( "<%=j render @post %>");
alert("Post is created successfully");
<%end %>

app/views/posts/edit.html.erb
<h3 class="text-center">Update a Post Details</h3>
<%= render 'posts/form' %>

app/views/posts/edit.js.erb
//$('#edit-post-block a').hide().parent();
//$('#post-new a').hide().parent().append("<%#= j render 'form' %>");
$("#post-modal").find(".modal-content").html("<%= j (render 'posts/form') %>");
$("#post-modal").modal('show');

app/views/posts/index.html.erb
 <div class="row">
   <div class="col-4"><h2 class="font-weight-bold text-uppercase">Listing all Posts <span class="badge badge-secondary"><%= "#{@posts.length}" %></span></h2></div>
   <div class="col-6">
     <%= render partial: 'date' %>
   </div>
   <div class="col-2">
  <% if @topic.present? %>
       <%= link_to "New Post", new_topic_post_path(@topic), remote: true, 'data-toggle' => "modal", 'data-target' => '#post-modal', class: "btn btn-success btn-sm new-post-btn ",id: "post-new", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>New Post... "} %>
       <%= link_to 'Back', topics_path, class: "btn btn-dark btn-sm btn-space" %>
  <% end %>

</div>

 </div><br>

<!---=================================Post modal=====================================================================-->
<div class="modal fade bd-example-modal-sm" id="post-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>
<!--================================================================================================================-->
<div id="index-post">
  <%= render partial: 'post' %> <!-- render the post from _post.html.erb-->
</div>

<!--  for default use- WillPaginate::ActionView::BootstrapLinkRenderer-->
<!-- for displaying in right side use  list_classes: %w(pagination justify-content-end) -->
<% if @posts.present? %>
  <%= will_paginate @posts, list_classes: %w(pagination justify-content-center), previous_label: "Previous", next_label: "Next", inner_window: 0, outer_window: 1 %>
<% end %>
<!---------------------------------------------------------------------------------------------------------------------->

app/views/posts/index.js.erb
<%if params[:start_date] >= params[:end_date] %>
$(".alert-danger").remove();
$("#dateErrorBlock").append('<div class="alert-danger"><%= escape_javascript(@errorDate[0])%></div>');
<%end %>

app/views/posts/new.html.erb
<h3 class="text-center">Create a Post</h3>
<%= render 'posts/form' %>

app/views/posts/new.js.erb

$("#post-modal").find(".modal-content").html("<%= j (render 'posts/form') %>");
$("#post-modal").modal('show');

app/views/posts/show.html.erb
<!--<div class="container-fluid">-->
  <div class="row">
    <div class=" col-md-11 bg-light">
      <div class="media">
        <span class="align-self-center mr-3"><%= image_tag(@post.image.url(:large))%></span>
        <div class="media-body">
          <h3 class="mt-0 font-weight-bold"><%= @post.name %></h3>
          <p> <%= @post.description %></p>
        </div>
      </div>
    </div>
    <div class="col-md-1">
      <%= link_to 'Back', topic_posts_path(@topic), class: "btn float-right btn-dark btn-sm btn-space" %>

    </div>
  </div>
<!--</div>-->
<br>

<hr>
<!---------------------------------------- Rating to display ---------------------------------------------------------->
<!--<div class="container px-lg-5">-->
  <div class="row">
<!--    " mx-lg-n5">-->
    <div class="col-6  py-3 px-lg-5 border bg-light">
      <h2 class=" font-weight-bold">Rate for the Post</h2>
      <% if @post.user != current_user %>
        <%= render "ratings/form", rating: Rating.new  %>
        <%else %>
      <p>Sorry U cant rate the Post</p>
      <% end %>
    </div>
    <div class="col-3 py-3 px-lg-5 border bg-light">
      <header>
        <h2 class=" font-weight-bold">Ratings</h2>
      </header>
<!--=============================================== using group--====================================================-->
      <div class="post-body">
        <%#  @result.each do |key, value| %>
<!--          <%#= key %> Star = <%#= value %><br>-->
        <%# end %>
<!--        <hr>`-->
<!--=================================== using group_by===============================================================-->
        <%  @result1.each do |key, value| %>
          <%if key !=nil %>
          <%= key %> Star = <%= value %><br>
        <% end %>
        <% end %>
      </div>
    </div>
    <!--==========================avg rate=================================================================-->
    <div class="col-3 py-3 px-lg-5 border bg-light">
      <h2 class=" font-weight-bold">Average Ratings:</h2>
      <% if @rate_avg.present? %>
        <%= @rate_avg.round(2) %>
      <%else %>
        <p>Rate the post</p>
      <%end %>
    </div>
  </div>
<!--=============================================comment session ========---------------------------------------------->
<!--<div class="container">-->
<!--  " px-lg-5">-->
  <div class="row">
<!--    " mx-lg-n5">-->
    <div class="col-6 py-3 px-lg-5 border bg-light">
<!--     py-3 px-lg-5 border bg-light">-->
      <div class="add-comment">
        <header>
          <h3 class=" font-weight-bold">Add Comment</h3>
        </header>
        <%= render "comments/form", comment: Comment.new %>
      </div>
    </div>
    <!--==============================Comments to display===============================================================-->
    <div class="col-6 py-3 px-lg-5 border bg-light">
<!--      " py-3 px-lg-5 border bg-light">-->
      <header>
        <h2 class="font-weight-bold">Comments <span class="badge badge-secondary"><%= "#{@post.comments_count }" %></span></h2>
      </header>

      <% if @post.comments.any? %>

        <% @comments.each do |comment| %>
          <hr>
          <div class="text-md font-weight-bold">
            <%= comment.name %>
          </div>
          <div class="comment-body">
            <%= comment.body %>
          </div>
          <div>
            <!--============================user comment ratings=================================================================-->

          <%= form_with url: user_comment_rate_topic_post_comment_path(@topic, @post, comment.id) do |form| %>
              <%= form.fields_for :user_comment_rating do |rat| %>
                <% if comment.user != current_user %>
                <% 1.upto(5) do |i| %>
                  <%= rat.radio_button :rate, i %>
                  <%= i %>
                <% end %>
                <%= form.button "Rate" ,data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Adding comments rate... "},class: 'btn btn-success btn-sm' %>
                <% end %>
              <% end %>

              <%= link_to 'details',comment_rate_show_topic_post_comment_path(@topic, @post, comment.id),class:"btn btn-info btn-sm" %>
            <% if can? :destroy, @post %><%= link_to 'delete',topic_post_comment_path(@topic, @post,comment), method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger btn-sm"%><%end %>
            <%end%>
          </div>

          <!--=================================================================================================================-->
        <% end %>
      <% else %>
        <p>There are no comments to show.</p>
      <% end %>

    </div>
  </div>
<!--</div>-->
<hr>

<!-- tags to display--------------------------------------------------------------------------------------------------->
<div class="col py-3 px-lg-5 border bg-light">
  <header>
    <h2 class=" font-weight-bold">All tags</h2>
  </header>
  <% if @post.tags.present? %>
    <% @post.tags.each do |tag| %>
      <%= link_to tag.tagname ,tag_path(tag), class:"btn btn-sm btn-outline-dark" %>
    <% end %>

  <% end %>
</div>
<hr>


<!---------------------------------------Ajax call for Read Status----------------------------------------------------->
<% unless @post.users.include?(current_user)%>
<%#= hidden_field_tag :topic_id, params[:topic_id] %>
<%#= hidden_field_tag :post_id, params[:id] %>
<script>

    $(document).ready(function () {
        $.ajax({
            method: "GET",
            url: '/topics/' + <%=params[:topic_id] %> + '/posts/' + <%=params[:id] %> + '/post_user_status'
        });
    });
</script>
<%end %>

app/views/posts/update.js.erb
<%if @post.errors.any? %>
$(".alert-danger").remove();
$("#postNameBlock").append('<div class="alert-danger"><%= escape_javascript(@post.errors['name'][0])%></div>');
$("#postDescBlock").append('<div class="alert-danger"><%= escape_javascript(@post.errors['description'][0])%></div>');
$("#postImgBlock").append('<div class="alert-danger"><%= escape_javascript(@post.errors['image'][0])%></div>');
$("#postTagBlock").append('<div class="alert-danger"><%= escape_javascript(@post.errors['tagname'][0])%></div>');
<%if@post.errors['name'][0] %>
$(".error-name-field").removeClass("is-invalid");
$(".error-name-field").addClass("is-valid")
<%else %>
$(".error-name-field").removeClass("is-valid");
$(".error-name-field").addClass("is-invalid")
<%end %>
<% if @post.errors['description'][0] %>
$(".error-desc-field").removeClass("is-invalid");
$(".error-desc-field").addClass("is-valid")
<% else %>
$(".error-desc-field").removeClass("is-valid");
$(".error-desc-field").addClass("is-invalid")
<%end %>
<%else %>
$('#edit-post-block a').show();
$('#post-new form').remove();
$('#post-new a').show();
$('#index-post').html("<%=j render @post %>");
<%end %>